export default {
  logoName: "WEB-Movie HALL",
  totalResults: 'total_results',
  totalPages: 'total_pages',
  movieName: "title",
  movieOrigName: "original_title",
  origLang: "original_language",
  tvName: "name",
  tvOrigName: "original_name",
  itemId: "id",
  itemImg: "poster_path",
  itemBackdropImg: "backdrop_path",
  itemOverview: "overview",
  itemRelease: "release_date",
  itemVote: "vote_average",
  topRatedMovies: 'Top Rated Movies',
  topRatedTVs: 'Top Rated TV Shows',
  feedback: 'Feedback',
  about: 'About Us',
  author: ' Yeuhen',
  authorLink: 'https://github.com/Yeuhen',
  git: 'Yeuhen',
  gitLink: 'https://github.com/Yeuhen',
  linkedIn: 'yevhen-yurchenko',
  linkedInLink: 'https://www.linkedin.com/in/yevhen-yurchenko/',
  searchNotFound: 'No results were found for your request. Please, change your query and try again.',
  recommended: 'Recomended'
};
