export default {
  logoName: 'WEB-Movie HALL',
  totalResults: 'total_results',
  totalPages: 'total_pages',
  movieName: 'title',
  movieOrigName: 'original_title',
  origLang: 'original_language',
  tvName: 'name',
  tvOrigName: 'original_name',
  itemId: 'id',
  itemImg: 'poster_path',
  itemBackdropImg: 'backdrop_path',
  itemOverview: 'overview',
  itemRelease: 'release_date',
  itemVote: 'vote_average',
  topRatedMovies: {
    'en-US': 'Top Movies',
    'ru-RU': 'Лучшие фильмы',
  },
  topRatedTVs: {
    'en-US': 'Top TV Shows',
    'ru-RU': 'Лучшие сериалы',
  },
  feedback: 'Feedback',
  about: {
    'en-US': 'About Us',
    'ru-RU': 'Про нас',
  },
  author: ' Yeuhen',
  authorLink: 'https://github.com/Yeuhen',
  git: 'Yeuhen',
  gitLink: 'https://github.com/Yeuhen',
  linkedIn: 'yevhen-yurchenko',
  linkedInLink: 'https://www.linkedin.com/in/yevhen-yurchenko/',
  searchNotFound: {
    'en-US': 'No results were found for your request. Please, change your query and try again.',
    'ru-RU': 'Ничего не найдено по вашему запросу или неверный адресс.',
  },
  recommended: 'Recomended',
};
